### ISSUE TITLE
Efficiency 3 Duplication

### ISSUE THREAD

**Issue by Melerion** [Choumiko/ModuleInserter#6]
Factorio version 0.15.21 (was also present on 0.15.18 and before)
ModuleInserter 2.0.3

Got a preset: Assembler 3, 3 Efficiency 3, 1 Speed 3

Efficiency 3s are inserted without any present in inventory or construction bots available other than those in personal inventory.

**Comment by Choumiko** [comment]
I think you caught ModuleInserter cheating. When the assembler is in a logistics network and the player doesn't have the modules but the network does, it simply takes the modules from the network, the bots still come from the player.

I can probably change it, so that in the case of missing modules it creates the vanilla proxy to insert the modules and then let the network take care of it.
