### ISSUE TITLE
Export/Import settings

### ISSUE THREAD

**Issue by dgw** [Choumiko/ModuleInserter#9]
As a new user of this mod, what I expected upon installing it was to find a new selection tool, like the built-in Upgrade Planner or modern versions of YARM. The current state, an item that costs nothing to make and can't be deleted, feels very Factorio 0.14 or 0.15.

Aside from modernizing the user's interactions with the mod to make it feel more like the built-in tools of 0.17, I think it would be useful to have Module Inserter be an Upgrade Planner–like item that players can store, share (via export string), drop, or delete _along with its configuration_ if desired.

Is this at all possible? Whether it would need someone like myself to submit a patch, or if you'd work on it yourself, right now I'm just curious if the idea would be entertained at all.

**Comment by Choumiko** [comment]
> As a new user of this mod, what I expected upon installing it was to find a new selection tool, like the built-in Upgrade Planner or modern versions of YARM. The current state, an item that costs nothing to make and can't be deleted, feels very Factorio 0.14 or 0.15.

That's mostly me forgetting to add it AND not being able to come up with a decent icon. So any suggestions are highly welcome. I was thinking some kind of arrow and a simple representation of a module (which is the hard part, since the small preview has very few pixels to work with)

> I think it would be useful to have Module Inserter be an Upgrade Planner–like item that players can store, share (via export string), drop, or delete _along with its configuration_ if desired.
> 
> Is this at all possible? Whether it would need someone like myself to submit a patch, or if you'd work on it yourself, right now I'm just curious if the idea would be entertained at all.

I can add a custom export/import functionality to the gui. The current planner types (blueprint, deconstruction, upgrade) don't allow saving the pairings that i need.

I'll take a look what I can get done over the weekend.

**Comment by Choumiko** [comment]
Turned it into a shortcut in the latest version with on optional keybinding (not set by default).
Export/Import will have to wait a bit, so i'm leaving the issue open.

**Comment by dgw** [comment]
Went looking in the changelog and found that this was implemented [in 5.1.0](https://github.com/Choumiko/ModuleInserter/blob/e87e30684eb16e840d95d6b93b362bc7e2e0c0b3/changelog.txt#L88).

Haven't played much lately, but thank you!
